### ISSUE TITLE
PiN and PiS

### ISSUE THREAD

**Issue by peterdfields** [tatumdmortimer/popgen-stats#10]
Hi,

The outputs I'm seeing for PiN and PiS appear to be counts rather than estimates of Pi for syn and nonsyn sites. Do you have any ideas about what might be going wrong here?

**Comment by tatumdmortimer** [comment]
For PiN and PiS, Egglib does not output a per-site estimate. I've updated the script to also output the number of non-synonymous and synonymous sites as well.
