### ISSUE TITLE
Simple question for pool-seq

### ISSUE THREAD

**Issue by jblamyatifremer** [tatumdmortimer/popgen-stats#8]
Dear popgen-stats creators, 

After parsing your readme.md, I come with a question : 
Does your selectionStats.py have been done for haploids organisms and pooled libraries ?
In other terms, do you implement algorithm from Achaz et al 2008, or the recent extension from Korneliussen et al 2013 or you use your own procedure ? 

Best regards, 

JB

**Comment by tatumdmortimer** [comment]
The selectionStats.py script uses the EggLib package (version 2) for calculating statistics. More information on this package can be found at http://mycor.nancy.inra.fr/egglib/ and De Mita et al. 2012. We use these scripts for haploid organisms but not for pooled libraries. If you are interested in analyzing pool-seq data, I would suggest something like PoPoolation.
